apiVersion: apps/v1
kind: Deployment
metadata:
  name: medi-share-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: medi-share
      version: v1
  template:
    metadata:
      labels:
        app: medi-share
        version: v1
    spec:
      containers:
        - name: medi-share-container
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
